### ISSUE TITLE
Header is overlayed by scroll content

### ISSUE THREAD

**Issue by poetworrier** [blobcatz/pebble-mastodon-theme#1]
See the attached image. Prob need to have a filler to hide the scroll? CSS isnt my forte

![Screenshot 2023-11-03 at 10 35 19 AM](https://github.com/blobcatz/pebble-mastodon-theme/assets/149641786/fe47b9ab-43d3-484b-96a9-98ec7088f320)

**Comment by poetworrier** [comment]
needs to set ui__Header background to #0d0d0d for the media type `@media screen and (max-width: 1174px)`

**Comment by blobcatz** [comment]
Fixed with 4c13fda

**Comment by poetworrier** [comment]
you're fast!
