### ISSUE TITLE
Issue - Light Theme - Pebble Logo Text Colour In Announcement Box

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#10]
With the light theme activated the colour of the pebble logo text in the annoucement box is incorrect should be black but is white

<img width="987" alt="Screenshot 2023-11-04 at 18 15 25" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/0c008c7e-1679-4a01-a0e5-bbc80cc4c9e3">

Logo displ;ayed is the same as displayed for Light Theme annoucement box and displays ok for Dark and High Contrast

**Comment by blobcatz** [comment]
Not caused by the theme. It's a custom-uploaded logo uploaded by pebble.social admins
