### ISSUE TITLE
Issue - The "notify me" and "menu" buttons on profiles do not show an icon (& other oddities)

### ISSUE THREAD

**Issue by ylemty** [blobcatz/pebble-mastodon-theme#11]
This may be intentional, but I wanted to submit it just in case:

When visiting someone's profile, the "notify me when this user posts" and "menu" icons to the right of the follow button are blank:

![Screenshot 2023-11-04 181705](https://github.com/blobcatz/pebble-mastodon-theme/assets/84487814/436ea044-7fcd-4f85-8a96-4ba5a4fa1877)

When either is clicked, icons do appear:

![Screenshot 2023-11-04 182124](https://github.com/blobcatz/pebble-mastodon-theme/assets/84487814/e15c6130-4877-4d8c-8c8a-2338c74370a2)

Lastly, when the notifications icon is activated then deactivated, there seems to be a lighter color filling the circle:

![Screenshot 2023-11-04 182420](https://github.com/blobcatz/pebble-mastodon-theme/assets/84487814/bc3a4ad4-97b8-4e8b-9e2d-c9a6308760fe)

Tested in Firefox, theme version 1.0.6, with both the light and dark themes.

**Comment by marklynch-tech** [comment]
I see this as well in Chrome. At least in profile, it might be a class called "fa fa-ellipsis-v fa-fw". Also isn't visible in hover state, but does have the X appear on click with menu open. 
![image](https://github.com/blobcatz/pebble-mastodon-theme/assets/83675147/e126650a-4f1b-4af5-8c26-617cace61a95)

**Comment by blobcatz** [comment]
Fixed
![image](https://github.com/blobcatz/pebble-mastodon-theme/assets/149013930/0726e07c-8a81-457f-a332-7ba46736df6c)
![image](https://github.com/blobcatz/pebble-mastodon-theme/assets/149013930/9369d77b-150a-4fd7-a31d-9b92abf24dfa)
