### ISSUE TITLE
Issue - Profile Theming Buttons and Links

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#12]
User Profile theming issues

"Notify me when user posts" and "Menu" buttons are not clear as to their purpose

Date joined and each following end user added profile links could do with line breaks after them

<img width="613" alt="Screenshot 2023-11-05 at 22 35 58" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/cd6e3786-d5ce-4261-97e6-bef4d36d1a41">

**Comment by blobcatz** [comment]
The first problem has already been fixed (#11) 
Will look into the second one later
