### ISSUE TITLE
Issue - Adding Users To Lists

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#14]
On trying to add a user to a list the + icon in the box is not visible before rollover or on rollover

<img width="588" alt="Screenshot 2023-11-06 at 19 03 48" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/c2d798a5-b0eb-49fc-a8cb-0d4e85dac031">

**Comment by blobcatz** [comment]
Fixed with 4cc1a35
