### ISSUE TITLE
Feature Request - Repost button needs some Razzle Dazzle

### ISSUE THREAD

**Issue by Hann8n** [blobcatz/pebble-mastodon-theme#15]
Love the animation put on the "like" / "heart" button. Would like to see that on the repost button as well 🙏

**Comment by blobcatz** [comment]
The like animation is from Mastodon and I'm neither an icon designer or animator but I'll see what I can do!

**Comment by blobcatz** [comment]
Finally made it a thing with v1.3.0, closing it now
