### ISSUE TITLE
Query - Icon theming in Bookmarks and Favourites

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#16]
When a user has navigated to Bookmarks or Favourities from the main menu should the icons be themed/coloured purple like Home, Notifications, Explore, Live Feeds, Private Mentions and Lists?

<img width="127" alt="Screenshot 2023-11-07 at 16 14 51" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/b034d3d4-9fbd-4e73-97da-cadaaf3ecd7e">

<br>

<img width="127" alt="Screenshot 2023-11-07 at 16 19 16" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/82f1fd6d-6222-4c2f-8d7c-6211093ef934">

**Comment by blobcatz** [comment]
That's weird, it is themed correctly for me

**Comment by daw50n** [comment]
Can see it on mobile and desktop using pebble.social with the dark theme selected
