### ISSUE TITLE
When Installed it Breaks the Mastodon (High Contrast) theme

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#2]
The theme is now active on pebble.social, but when a user goes into preferences and selects Mastodon (High Contrast) it adopts a white theme as the baseline for the background rather than black and not all text can be read.

<img width="1241" alt="Screenshot 2023-11-03 at 18 14 42" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/d74a7baa-dad3-4f3a-9878-391a9b0db44d">

**Comment by blobcatz** [comment]
This is how far I've got right now. Never worked with high contrasted themes, so I would really want feedback on what to change.
![image](https://github.com/blobcatz/pebble-mastodon-theme/assets/149013930/afeb0039-ccee-482c-8af0-8857678c99a1)

**Comment by daw50n** [comment]
The Mastodon default seems to make the grey text white - the pebble dark is almost hight contrast already (apart from the grey text remaining in liked statuses and the private message tab)

**Comment by blobcatz** [comment]
Should be fixed with 01c3b8d, closing it now but raise anything if there's something to change with improving the contrast (or there being something I missed)
