### ISSUE TITLE
Like duplicating on navigation bar

### ISSUE THREAD

**Issue by dotcoco0** [blobcatz/pebble-mastodon-theme#30]
L
![InShot_20240202_171344325](https://github.com/blobcatz/pebble-mastodon-theme/assets/158621923/84fbf79d-5114-49e2-91d1-4f60ceb53147)

**Comment by blobcatz** [comment]
can't repro
![image](https://github.com/blobcatz/pebble-mastodon-theme/assets/149013930/9637705a-d459-48e8-b620-f917f6730fb2)

**Comment by dotcoco0** [comment]
This was the . Style
