### ISSUE TITLE
Invisible arrows on announcements

### ISSUE THREAD

**Issue by marino** [blobcatz/pebble-mastodon-theme#31]
When there are more than one announcement, previous and next arrows at both sides of number of announcement are invisible, both light and dark theme

Arrows should appear at both sides of "1/2", bottom right. When hovering, color changes but no arrow or indicator either.

![imagen](https://github.com/blobcatz/pebble-mastodon-theme/assets/38074/90b7f0b1-5dac-4356-83d0-f0116ab2e536)

**Comment by blobcatz** [comment]
fixed with 19399743e5357f76f0da8533fa96f27e524ef966
