### ISSUE TITLE
Issue - Black Theme - Grey text displayed rather than white

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#4]
With the black theme activated some text is shown as grey rather than white which is hard to read. Examples as follows:

Raised on Pebble.social running 1.0.2

Example 1
Seen in notifications - All tab where a user favourites a status

<img width="1228" alt="Notifications Tab" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/728b11da-1f43-4787-b72d-ca7e06b2a33c">

Example 2
Seen in the private mentions tab for the message text received in a message

<img width="1227" alt="Private Conversations" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/33bffe97-9a7c-4add-8f7d-7fe8936841de">

**Comment by blobcatz** [comment]
The first one is intentional. Favouriting/boosting a post of yours has gray text also on Mastodon's default theme, as it's meant to be a preview of your post,  the contrast is obviously higher on "high contrast" theme.
