### ISSUE TITLE
Issues - Search Entry Not Being Changed to Explore

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#5]
Using version 1.04 (not installed on pebble.social) there seems an issue with the Search menu not being remapped to Explore and the # icon missing and no animated icon when clicked.

<img width="1198" alt="Screenshot 2023-11-03 at 20 49 49" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/387a5525-1ace-4f2e-9100-5f7d1de3e4eb">

**Comment by blobcatz** [comment]
That's weird, can you show me what classes the "Search" tab on the sidebar has? Neither of the instances I am on have it so it's hard to tell what's wrong by myself

**Comment by daw50n** [comment]
Not exactly sure what you need but applied 1.0.5 and took the following screenshot
<img width="1335" alt="Screenshot 2023-11-04 at 16 01 10" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/34c34f97-9eaf-4595-89e4-b99148454f3b">

Prodding around in the admin settings I note I have Enable Trends turned off - with it turned on it displays the themed explore like on pebble.social (so wasn't linked to running in single user instance mode).

<img width="1203" alt="Screenshot 2023-11-04 at 16 12 53" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/7133cf59-8ab0-4e3a-a8bd-4c1ee657437d">

**Comment by blobcatz** [comment]
Fixed with 457d0bc

**Comment by daw50n** [comment]
Does not appear fixed in 1.0.6

**Comment by blobcatz** [comment]
Pull from latest, it's not fixed in 1.0.6 as I fixed it *after* publishing 1.0.6
