### ISSUE TITLE
Feature Request - Colour of Emoji When Rolled Over

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#8]
Should/could the Emoji smiley yellow colour be themed purple on roll over?

<img width="413" alt="Screenshot 2023-11-04 at 17 12 52" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/208cb904-9c56-42fe-bd76-2ca914b2c035">

**Comment by blobcatz** [comment]
What about replacing it with a smile emoji that looks like the Pebble logo?
![image](https://github.com/blobcatz/pebble-mastodon-theme/assets/149013930/0f44da26-68e0-4691-87db-dd1f2e8a123e)

**Comment by daw50n** [comment]
Even better 👍🏻

**Comment by blobcatz** [comment]
Added with d921dce
