### ISSUE TITLE
Query - Roll Over On Private Mentions 

### ISSUE THREAD

**Issue by daw50n** [blobcatz/pebble-mastodon-theme#9]
Query - Should/Could the roll over colour on private messages be purple themed?

<img width="331" alt="Screenshot 2023-11-04 at 17 26 15" src="https://github.com/blobcatz/pebble-mastodon-theme/assets/149823293/e52714dd-dfdd-4e48-8843-525ba66113d9">

**Comment by blobcatz** [comment]
The goal of the theme is to resemble T2/Pebble as close as possible. The icon was also blue on T2/Pebble, so I'm going to keep it this way.
